backend/django_gallery/albums/urls.py
from albums import views
from django.urls import re_path

app_name = 'albums'

urlpatterns = [
    re_path(
        r"(?P<album_slug>[A-Za-z_1-9-]+)/?",
        views.AlbumView.as_view(), name="album"
    ),
]

backend/django_gallery/django_gallery/urls.py
from admin_site.admin import admin_staff_site
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('staff/', admin_staff_site.urls, name='staff'),
    path("", include("static_site.urls")),
    path("album/", include("albums.urls"))
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/django_gallery/static_site/urls.py
from django.urls import path

from . import views

app_name = 'static_site'

urlpatterns = [
    path("", views.IndexView, name="index"),
    path("contacts", views.ContactView, name="contacts")
]

backend/django_gallery/templates/includes/footer.html
{% load static %}
<footer class="page__footer footer">
	<div class="grid grid--full">
		<div class="footer__container">
			<div class="flex-item item-2">
				<a href="{{ site_appearence.vk_link }}" target="blank"><img src="{% static '/dis/fa-vk.png' %}" alt="" width="21"></a>
				<a href="{{ site_appearence.ints_link }}" target="blank"><img src="{% static '/dis/fa-instagram.png' %}" alt="" width="21"></a>
				<a href="{{ site_appearence.tg_link }}" target="blank"><img src="{% static '/dis/fa-telegram.png' %}" alt="" width="21"></a>
				<div class="footer__copyright">{{ site_appearence.copyright}}</div>
			</div>
			<div class="flex-item item-3">
				<div class="footer__copyright">Все изображения и тексты принадлежат автору.</div>
				<div class="footer__copyright"> Использование материалов допустимо при предварительном согласии.</div>
			</div>
		</div>
	</div>
</footer>

backend/django_gallery/templates/includes/head_for_all.html
<meta charset=UTF-8>
	<meta name="viewport" content="user-scalable=no, initial-scale=0.1, maximum-scale=1, minimum-scale=1, width=device-width">
	<meta name="mobile-web-app-capable" content="yes">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Prosto+One&display=swap" rel="stylesheet">
	<link href="/static/styles/body.css" rel="stylesheet">
	<link rel="stylesheet" media="screen and (max-width: 770px)" href="/static/styles/menu_mob.css?s028">
	<link rel="stylesheet" media="screen and (min-width: 770px)" href="/static/styles/main_menu.css?s028">
	<link rel="stylesheet" href="/static/styles/footer2.css?s033">
	<script src="/static/js/menu_mob.js??s028"></script>

backend/django_gallery/templates/includes/main_menu.html
<div>
    <div class="menu-icon menu-menu"></div>
</div>
<div class="menu-overlay" style="display: none;"></div>
<div class="menu-positioner">
    <div class="menu-wrapper menu-wrapper_animate">
        <div class="menu-container">
            <ul>
                <li><a href="{% url 'static_site:index'%}">Главная</a></li>
                    {% for highest_section, daughter_sections_and_albums in sections.items %}        
                        {%with dict=daughter_sections_and_albums template="includes/treedict.html"%}
                            <li><span>{{ highest_section | upper }}</span>
                            <ul>
                                {% include template %}
                            </ul>
                            </li>
                            {% endwith %}
                    {% endfor %}
                {% for album in best_albums %}
                    <li><span><a href="{% url 'albums:album' album_slug=album.slug %}">{{ album.title | upper }}</a></span>
                {% endfor %}
                <li><a href="{% url 'static_site:contacts'%}">Контакты</a></li>
            </ul>
        </div>
    </div>
</div>

backend/django_gallery/templates/includes/scroll_button.html
{% load static%}
<a class="scrollhoch" href="#" style="right: 30px; display: inline;">
    <span><img src="{% static '/dis/up.png' %}"></span>
    </a>

backend/django_gallery/templates/includes/treedict.html
{% with  section_albums=dict.section_albums daughter_sections=dict.daughter_sections %}
    {% for album in section_albums%}
        <li>  
        <a href="{% url 'albums:album' album_slug=album.slug %}">
            {{ album.title | upper }}</a>
        </li>
    {% endfor %}
        {% for daughter_section, nested in daughter_sections.items %}
        {% if nested.section_albums|length == 0 and nested.daughter_sections|length == 0%}
        <li>{{ daughter_section.title | upper }}
        {% else %}
        <li><span>{{ daughter_section.title | upper }}</span>
        {% endif %}
            <ul>
            {%with dict=nested template="includes/treedict.html" %}
                {%include template%}
            {%endwith%}
            </ul>
        </li>
        {% endfor%}
    {% endwith %}